% createSplineFit.m
% Generated by cftool for ADF
% Fit a smoothing spline to x and y data. 


function [fitresult, gof] = createSplineFit(x, y, smooth)

% Handle inputs
    if nargin < 3; smooth = 0.000835584228530174; end

% Set up data
    [xData, yData] = prepareCurveData( x, y );

% Set up fittype and options.
    ft = fittype( 'smoothingspline' );
    opts = fitoptions( 'Method', 'SmoothingSpline' );
    opts.SmoothingParam = smooth;

% Fit model to data.
    [fitresult, gof] = fit( xData, yData, ft, opts );




